my second second commit
SureshKhandale/GitVerjet pull request #3
Opened 2023-04-18 06:43 UTC by sonalitchaudhari

please check the code

2023-04-18 06:46 UTC, SureshKhandale requested changes

2023-04-18 06:46 UTC, SureshKhandale commented on src/test/java/com/signup/Sonali1.java
> +System.out.println("my second commit");
plz add some line below

2023-04-18 06:53 UTC, sonalitchaudhari commented on src/test/java/com/signup/Sonali1.java
> +System.out.println("my second commit");
ok

2023-04-18 07:06 UTC, SureshKhandale approved these changes

2023-04-18 07:09 UTC, merged

2023-04-22 12:41 UTC, sonalitchaudhari commented
ok